/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AccountMergeInner
 */
export interface AccountMergeInner {
    /**
     * 
     * @type {number}
     * @memberof AccountMergeInner
     */
    'merge_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountMergeInner
     */
    'new_account_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountMergeInner
     */
    'old_account_id'?: number;
}

