/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditorBadgeCounts } from './answers-inner-last-editor-badge-counts';

/**
 * 
 * @export
 * @interface AnswersInnerLastEditor
 */
export interface AnswersInnerLastEditor {
    /**
     * 
     * @type {number}
     * @memberof AnswersInnerLastEditor
     */
    'accept_rate'?: number;
    /**
     * 
     * @type {AnswersInnerLastEditorBadgeCounts}
     * @memberof AnswersInnerLastEditor
     */
    'badge_counts'?: AnswersInnerLastEditorBadgeCounts;
    /**
     * 
     * @type {string}
     * @memberof AnswersInnerLastEditor
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswersInnerLastEditor
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswersInnerLastEditor
     */
    'profile_image'?: string;
    /**
     * 
     * @type {number}
     * @memberof AnswersInnerLastEditor
     */
    'reputation'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnswersInnerLastEditor
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AnswersInnerLastEditor
     */
    'user_type'?: string;
}

