/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface BadgesInner
 */
export interface BadgesInner {
    /**
     * 
     * @type {string}
     * @memberof BadgesInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof BadgesInner
     */
    'award_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof BadgesInner
     */
    'badge_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BadgesInner
     */
    'badge_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgesInner
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgesInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgesInner
     */
    'rank'?: string;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof BadgesInner
     */
    'user'?: AnswersInnerLastEditor;
}

