/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface CreatedComment
 */
export interface CreatedComment {
    /**
     * 
     * @type {string}
     * @memberof CreatedComment
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedComment
     */
    'body_markdown'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatedComment
     */
    'can_flag'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreatedComment
     */
    'comment_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatedComment
     */
    'creation_date'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreatedComment
     */
    'edited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatedComment
     */
    'link'?: string;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof CreatedComment
     */
    'owner'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {number}
     * @memberof CreatedComment
     */
    'post_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatedComment
     */
    'post_type'?: string;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof CreatedComment
     */
    'reply_to_user'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {number}
     * @memberof CreatedComment
     */
    'score'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreatedComment
     */
    'upvoted'?: boolean;
}

