/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrorsInner
 */
export interface ErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorsInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorsInner
     */
    'error_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorsInner
     */
    'error_name'?: string;
}

