/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EventsInner
 */
export interface EventsInner {
    /**
     * 
     * @type {number}
     * @memberof EventsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof EventsInner
     */
    'event_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsInner
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsInner
     */
    'link'?: string;
    /**
     * 
     * @type {number}
     * @memberof EventsInner
     */
    'the id of the object (answer, comment, question, or user) the event describes'?: number;
}

