/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InboxItemsInnerSiteStyling
 */
export interface InboxItemsInnerSiteStyling {
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSiteStyling
     */
    'link_color'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSiteStyling
     */
    'tag_background_color'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSiteStyling
     */
    'tag_foreground_color'?: string;
}

