/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboxItemsInnerSiteStyling } from './inbox-items-inner-site-styling';

/**
 * 
 * @export
 * @interface InboxItemsInnerSite
 */
export interface InboxItemsInnerSite {
    /**
     * 
     * @type {Array<any>}
     * @memberof InboxItemsInnerSite
     */
    'aliases'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'api_site_parameter'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'audience'?: string;
    /**
     * 
     * @type {number}
     * @memberof InboxItemsInnerSite
     */
    'closed_beta_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'favicon_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'high_resolution_icon_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'icon_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof InboxItemsInnerSite
     */
    'launch_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'logo_url'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof InboxItemsInnerSite
     */
    'markdown_extensions'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof InboxItemsInnerSite
     */
    'open_beta_date'?: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof InboxItemsInnerSite
     */
    'related_sites'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'site_state'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'site_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'site_url'?: string;
    /**
     * 
     * @type {InboxItemsInnerSiteStyling}
     * @memberof InboxItemsInnerSite
     */
    'styling'?: InboxItemsInnerSiteStyling;
    /**
     * 
     * @type {string}
     * @memberof InboxItemsInnerSite
     */
    'twitter_account'?: string;
}

