/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboxItemsInnerSite } from './inbox-items-inner-site';

/**
 * 
 * @export
 * @interface InfoObject
 */
export interface InfoObject {
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'answers_per_minute'?: number;
    /**
     * 
     * @type {string}
     * @memberof InfoObject
     */
    'api_revision'?: string;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'badges_per_minute'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'new_active_users'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'questions_per_minute'?: number;
    /**
     * 
     * @type {InboxItemsInnerSite}
     * @memberof InfoObject
     */
    'site'?: InboxItemsInnerSite;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_accepted'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_answers'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_badges'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_comments'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_questions'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_unanswered'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_users'?: number;
    /**
     * 
     * @type {number}
     * @memberof InfoObject
     */
    'total_votes'?: number;
}

