/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditorBadgeCounts } from './answers-inner-last-editor-badge-counts';

/**
 * 
 * @export
 * @interface NetworkUsersInner
 */
export interface NetworkUsersInner {
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'account_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'answer_count'?: number;
    /**
     * 
     * @type {AnswersInnerLastEditorBadgeCounts}
     * @memberof NetworkUsersInner
     */
    'badge_counts'?: AnswersInnerLastEditorBadgeCounts;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'last_access_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'question_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'reputation'?: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkUsersInner
     */
    'site_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkUsersInner
     */
    'site_url'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof NetworkUsersInner
     */
    'top_answers'?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof NetworkUsersInner
     */
    'top_questions'?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof NetworkUsersInner
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkUsersInner
     */
    'user_type'?: string;
}

