/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboxItemsInnerSite } from './inbox-items-inner-site';

/**
 * 
 * @export
 * @interface NotificationsInner
 */
export interface NotificationsInner {
    /**
     * 
     * @type {string}
     * @memberof NotificationsInner
     */
    'body'?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationsInner
     */
    'is_unread'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationsInner
     */
    'notification_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationsInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {InboxItemsInnerSite}
     * @memberof NotificationsInner
     */
    'site'?: InboxItemsInnerSite;
}

