/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface PostsInner
 */
export interface PostsInner {
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'body_markdown'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'comment_count'?: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof PostsInner
     */
    'comments'?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'down_vote_count'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostsInner
     */
    'downvoted'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'last_activity_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'last_edit_date'?: number;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof PostsInner
     */
    'last_editor'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'link'?: string;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof PostsInner
     */
    'owner'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'post_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'score'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostsInner
     */
    'share_link'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostsInner
     */
    'up_vote_count'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostsInner
     */
    'upvoted'?: boolean;
}

