/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PrivilegesInner
 */
export interface PrivilegesInner {
    /**
     * 
     * @type {string}
     * @memberof PrivilegesInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PrivilegesInner
     */
    'reputation'?: number;
    /**
     * 
     * @type {string}
     * @memberof PrivilegesInner
     */
    'short_description'?: string;
}

