/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QuestionsInnerNotice
 */
export interface QuestionsInnerNotice {
    /**
     * 
     * @type {string}
     * @memberof QuestionsInnerNotice
     */
    'body'?: string;
    /**
     * 
     * @type {number}
     * @memberof QuestionsInnerNotice
     */
    'creation_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionsInnerNotice
     */
    'owner_user_id'?: number;
}

