/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QuestionsInnerClosedDetails
 */
export interface QuestionsInnerClosedDetails {
    /**
     * 
     * @type {string}
     * @memberof QuestionsInnerClosedDetails
     */
    'description'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof QuestionsInnerClosedDetails
     */
    'by_users'?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof QuestionsInnerClosedDetails
     */
    'on_hold'?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof QuestionsInnerClosedDetails
     */
    'original_questions'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof QuestionsInnerClosedDetails
     */
    'reason'?: string;
}

