/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReputationHistoryInner
 */
export interface ReputationHistoryInner {
    /**
     * 
     * @type {number}
     * @memberof ReputationHistoryInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReputationHistoryInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReputationHistoryInner
     */
    'reputation_change'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReputationHistoryInner
     */
    'reputation_history_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReputationHistoryInner
     */
    'user_id'?: number;
}

