/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReputationChangesInner
 */
export interface ReputationChangesInner {
    /**
     * 
     * @type {string}
     * @memberof ReputationChangesInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReputationChangesInner
     */
    'link'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReputationChangesInner
     */
    'on_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReputationChangesInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReputationChangesInner
     */
    'post_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReputationChangesInner
     */
    'reputation_change'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReputationChangesInner
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReputationChangesInner
     */
    'vote_type'?: string;
}

