/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SingleFilter
 */
export interface SingleFilter {
    /**
     * 
     * @type {string}
     * @memberof SingleFilter
     */
    'filter'?: string;
    /**
     * 
     * @type {string}
     * @memberof SingleFilter
     */
    'filter_type'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof SingleFilter
     */
    'included_fields'?: Array<any>;
}

