/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface SuggestedEditsInner
 */
export interface SuggestedEditsInner {
    /**
     * 
     * @type {Array<any>}
     * @memberof SuggestedEditsInner
     */
    'tags'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof SuggestedEditsInner
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof SuggestedEditsInner
     */
    'approval_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof SuggestedEditsInner
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestedEditsInner
     */
    'comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof SuggestedEditsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof SuggestedEditsInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SuggestedEditsInner
     */
    'post_type'?: string;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof SuggestedEditsInner
     */
    'proposing_user'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {number}
     * @memberof SuggestedEditsInner
     */
    'rejection_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof SuggestedEditsInner
     */
    'suggested_edit_id'?: number;
}

