/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface TagWikisInner
 */
export interface TagWikisInner {
    /**
     * 
     * @type {string}
     * @memberof TagWikisInner
     */
    'body'?: string;
    /**
     * 
     * @type {number}
     * @memberof TagWikisInner
     */
    'body_last_edit_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof TagWikisInner
     */
    'excerpt'?: string;
    /**
     * 
     * @type {number}
     * @memberof TagWikisInner
     */
    'excerpt_last_edit_date'?: number;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof TagWikisInner
     */
    'last_body_editor'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof TagWikisInner
     */
    'last_excerpt_editor'?: AnswersInnerLastEditor;
    /**
     * 
     * @type {string}
     * @memberof TagWikisInner
     */
    'tag_name'?: string;
}

