/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TagSynonymsInner
 */
export interface TagSynonymsInner {
    /**
     * 
     * @type {number}
     * @memberof TagSynonymsInner
     */
    'applied_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof TagSynonymsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof TagSynonymsInner
     */
    'from_tag'?: string;
    /**
     * 
     * @type {number}
     * @memberof TagSynonymsInner
     */
    'last_applied_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof TagSynonymsInner
     */
    'to_tag'?: string;
}

