/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnswersInnerLastEditor } from './answers-inner-last-editor';

/**
 * 
 * @export
 * @interface TagScoreObjectsInner
 */
export interface TagScoreObjectsInner {
    /**
     * 
     * @type {number}
     * @memberof TagScoreObjectsInner
     */
    'post_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof TagScoreObjectsInner
     */
    'score'?: number;
    /**
     * 
     * @type {AnswersInnerLastEditor}
     * @memberof TagScoreObjectsInner
     */
    'user'?: AnswersInnerLastEditor;
}

