/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TagsInner
 */
export interface TagsInner {
    /**
     * 
     * @type {number}
     * @memberof TagsInner
     */
    'count'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TagsInner
     */
    'has_synonyms'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TagsInner
     */
    'is_moderator_only'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TagsInner
     */
    'is_required'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TagsInner
     */
    'last_activity_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof TagsInner
     */
    'name'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof TagsInner
     */
    'synonyms'?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof TagsInner
     */
    'user_id'?: number;
}

