/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TopTagObjectsInner
 */
export interface TopTagObjectsInner {
    /**
     * 
     * @type {number}
     * @memberof TopTagObjectsInner
     */
    'answer_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopTagObjectsInner
     */
    'answer_score'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopTagObjectsInner
     */
    'question_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopTagObjectsInner
     */
    'question_score'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopTagObjectsInner
     */
    'tag_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TopTagObjectsInner
     */
    'user_id'?: number;
}

