/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserTimelineObjectsInner
 */
export interface UserTimelineObjectsInner {
    /**
     * 
     * @type {string}
     * @memberof UserTimelineObjectsInner
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'badge_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'comment_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'creation_date'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserTimelineObjectsInner
     */
    'detail'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTimelineObjectsInner
     */
    'link'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'post_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserTimelineObjectsInner
     */
    'post_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'suggested_edit_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserTimelineObjectsInner
     */
    'timeline_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserTimelineObjectsInner
     */
    'user_id'?: number;
}

