/*
StackExchange

Stack Exchange is a network of 130+ Q&A communities including Stack Overflow.


The version of the OpenAPI document: 2.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WritePermissionsInner
 */
export interface WritePermissionsInner {
    /**
     * 
     * @type {boolean}
     * @memberof WritePermissionsInner
     */
    'can_add'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WritePermissionsInner
     */
    'can_delete'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WritePermissionsInner
     */
    'can_edit'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WritePermissionsInner
     */
    'max_daily_actions'?: number;
    /**
     * 
     * @type {number}
     * @memberof WritePermissionsInner
     */
    'min_seconds_between_actions'?: number;
    /**
     * 
     * @type {string}
     * @memberof WritePermissionsInner
     */
    'object_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof WritePermissionsInner
     */
    'user_id'?: number;
}

